[package]
name = "aoc2023"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
either = "1.9.0"
itertools = "0.12.0"
ndarray = "0.15.6"
num = "0.4.1"
pathfinding = "4.6.0"
z3 = "0.12.1"
