[package]
name = "aoc2024"
version = "0.1.0"
edition = "2021"

[workspace]
members = [".", "common"]

[dependencies]
aoc-common = { path = "common" }
itertools = "0.13.0"
memoize = "0.4.2"
ndarray = "0.16.1"
pathfinding = "4.11.0"
regex = "1.11.1"
